#!/bin/env bash

git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
git config --global alias.list "config --list"
git config --global alias.cfg "config"
git config --global alias.cfgl "config --list"
git config --global alias.st "status"
git config --global user.name "soarpenguin"
git config --global user.email "soarpenguin@gmail.com"

