#!/usr/bin/env bash

git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
git config --global alias.list "config --list"
git config --global alias.cfg "config"
git config --global alias.cfgl "config --list"
git config --global alias.st "status"
git config --global user.name "soarpenguin"
git config --global user.email "soarpenguin@gmail.com"

OS=`uname -s | tr '[A-Z]' '[a-z]'`
if [[ "$OS" == "darwin" || "$OS" == "linux" ]]; then
    git config --global core.autocrlf input
elif [ "$(expr substr $OS 1 5)" == "mingw" ]; then
    git config --global core.autocrlf true
fi

PRIVATE="off"
#set password cache for one day
if [ "x$PRIVATE" == "xon" ]; then
    git config --global credential.helper cache
    git config --global credential.helper 'cache --timeout=36000'
fi

