#!/usr/bin/env bash

#set -x
export PS4='+ [`basename ${BASH_SOURCE[0]}`:$LINENO ${FUNCNAME[0]} \D{%F %T} $$ ] '

AUTO_INVOKE_SUDO=yes;
CURDIR=$(cd "$(dirname "$0")"; pwd)
DEST="~/.vim/bundle/"
CURUSER=$(who | head -1 | awk '{print $1}')

function _invoke_sudo()
{
    if [ "`id -u`" != "`id -u $1`" ]; then
        echo "`whoami`:you need to be $1 privilege to run this script.";
        if [ "$AUTO_INVOKE_SUDO" == "yes" ]; then
            echo "Invoking sudo ...";
            sudo -u "#`id -u $1`" bash -c "$2";
        fi
        exit 0;
    fi
}

UID=`id -u`
if [ $UID -ne '0' ]; then
    _invoke_sudo root "${CURDIR}/$0 $@"
fi

sudo apt-get -y install build-essential cmake
sudo apt-get -y install python-dev

exit 0

git clone https://github.com/gmarik/Vundle.vim.git $DEST/Vundle.vim

if [ "x$DEST" != "x" ]; then
    mkdir -p "$DEST"
fi

if [ -d "$DEST " ]; then
    cd $DEST && git clone https://github.com/Valloric/YouCompleteMe.git
    if [ -d "$DEST/YouCompleteMe" ]; then
        cd "$DEST/YouCompleteMe/" && git submodule update --init --recursive
    fi
fi


debug=1
function _log()
{
        local epath=$(pwd)
        local timestamp=$(date +%Y%m%d-%H:%M:%S)
        #echo "#######################################################################"
        echo "[$timestamp][$epath]$1"
}

function _do_cmd()
{
    _log "[exec] $*   please wait............"
    if [ $debug -eq 1 ]; then
        $@
    else
        $@ >/dev/null 2>&1
    fi

    if [[ $? -ne 0 ]]; then
        _log "[fail] $@"
        exit 1
    else
        _log "[succ] $@"
    fi
}

