#!/usr/bin/env bash

AUTO_INVOKE_SUDO=yes;
curdir=$(dirname $(readlink -f $0))
DEST="~/.vim/bundle/"
curuser=$(who | head -1 | awk '{print $1}')

function invoke_sudo() 
{
    if [ "`id -u`" != "`id -u $1`" ]; then
        echo "`whoami`:you need to be $1 privilege to run this script.";
        if [ "$AUTO_INVOKE_SUDO" == "yes" ]; then 
            echo "Invoking sudo ...";
            sudo -u "#`id -u $1`" bash -c "$2";
        fi
        exit 0;
    fi
}

uid=`id -u`
if [ $uid -ne '0' ]; then 
    invoke_sudo root "${curdir}/$0 $@"
fi

sudo apt-get -y install build-essential cmake
sudo apt-get -y install python-dev

exit 0

git clone https://github.com/gmarik/Vundle.vim.git $DEST/Vundle.vim

if [ "x$DEST" != "x" ]; then
    mkdir -p "$DEST"
fi

if [ -d "$DEST " ]; then
    cd $DEST && git clone https://github.com/Valloric/YouCompleteMe.git
    if [ -d "$DEST/YouCompleteMe" ]; then
        cd "$DEST/YouCompleteMe/" && git submodule update --init --recursive
    fi
fi


debug=1
function log()
{    
        local epath=$(pwd)
        local timestamp=$(date +%Y%m%d-%H:%M:%S)
        #echo "#######################################################################"    
        echo "[$timestamp][$epath]$1"  
}

function do_cmd()
{    
        log "[exec] $*   please wait............"
        if [ $debug -eq 1 ];then    
                $@    
        else    
                $@ >/dev/null 2>&1    
        fi  
        if [[ $? -ne 0 ]];then
                log "[fail] $@" 
                exit 1 
        else
                log "[succ] $@"
        fi  
}

